version: '3.8'
services:
  product-service:
    build:
      context: ../product-service
    ports:
      - "8001:8001"
    environment:
      - PRODUCT_SERVICE_PORT=8001
      - DATABASE_DSN=host=postgres user=postgres password=secret dbname=products port=5432 sslmode=disable
    depends_on:
      - postgres

  user-service:
    build:
      context: ../user-service
    ports:
      - "8002:8002"
    environment:
      - USER_SERVICE_PORT=8002
      - DATABASE_DSN=host=postgres user=postgres password=secret dbname=users port=5432 sslmode=disable
    depends_on:
      - postgres

  order-service:
    build:
      context: ../order-service
    ports:
      - "8003:8003"
    environment:
      - ORDER_SERVICE_PORT=8003
      - DATABASE_DSN=host=postgres user=postgres password=secret dbname=orders port=5432 sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
