// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ecommerce-microservices/common/config"
	"ecommerce-microservices/common/middleware"
	config2 "ecommerce-microservices/order-service/config"
	"ecommerce-microservices/user-service/handlers"
	"ecommerce-microservices/user-service/repository"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func InitializeRouter() (*mux.Router, error) {
	appConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	db, err := config2.NewDBConnection(appConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userHandler := handlers.NewUserHandler(userRepository)
	router := ProvideRouter(userHandler)
	return router, nil
}

// wire.go:

func ProvideRouter(handler *handlers.UserHandler) *mux.Router {
	router := mux.NewRouter()
	router.Use(middleware.LoggingMiddleware)
	router.HandleFunc("/register", handler.RegisterUser).Methods("POST")
	router.HandleFunc("/user", handler.GetUserByID).Methods("GET")
	return router
}
